name: CI/CD
on:
  push:
    branches: [ main ]
  pull_request: {}
env:
  node-version: 16.x
jobs:
  Install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
      - name: Install modules
        run: yarn install --frozen-lockfile
  Build:
    runs-on: ubuntu-latest
    needs: [Install]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
      - name: Install modules
        run: yarn install --frozen-lockfile
      - name: Generate
        run: yarn generate
      - name: Build
        run: yarn build
  Publish:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    needs: [ Build ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
          registry-url: https://registry.npmjs.org/
      - name: Install modules
        run: yarn install --frozen-lockfile
      - name: Generate
        run: yarn generate
      - name: Build
        run: yarn build
      - name: Publish
        run: yarn semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
